version: '3'
services:
  manager:
    container_name: manager
    ports:
      - "8080:8080"
    image: md5crack-manager
    build:
      context: .
      dockerfile: manager/Dockerfile
    networks:
      - md5crack-network
    environment:
      - WORKERS_COUNT=8
      - WORKER_HOST=worker
      - WORKER_PORT=8081

  worker-0:
    container_name: worker-0
    image: md5crack-worker
    build:
      context: .
      dockerfile: worker/Dockerfile
    networks:
      - md5crack-network
    environment:
      - MANAGER_HOST=manager
      - MANAGER_PORT=8080
  worker-1:
    container_name: worker-1
    image: md5crack-worker
    build:
      context: .
      dockerfile: worker/Dockerfile
    networks:
      - md5crack-network
    environment:
      - MANAGER_HOST=manager
      - MANAGER_PORT=8080
  worker-2:
    container_name: worker-2
    image: md5crack-worker
    build:
      context: .
      dockerfile: worker/Dockerfile
    networks:
      - md5crack-network
    environment:
      - MANAGER_HOST=manager
      - MANAGER_PORT=8080
  worker-3:
    container_name: worker-3
    image: md5crack-worker
    build:
      context: .
      dockerfile: worker/Dockerfile
    networks:
      - md5crack-network
    environment:
      - MANAGER_HOST=manager
      - MANAGER_PORT=8080
  worker-4:
    container_name: worker-4
    image: md5crack-worker
    build:
      context: .
      dockerfile: worker/Dockerfile
    networks:
      - md5crack-network
    environment:
      - MANAGER_HOST=manager
      - MANAGER_PORT=8080
  worker-5:
    container_name: worker-5
    image: md5crack-worker
    build:
      context: .
      dockerfile: worker/Dockerfile
    networks:
      - md5crack-network
    environment:
      - MANAGER_HOST=manager
      - MANAGER_PORT=8080
  worker-6:
    container_name: worker-6
    image: md5crack-worker
    build:
      context: .
      dockerfile: worker/Dockerfile
    networks:
      - md5crack-network
    environment:
      - MANAGER_HOST=manager
      - MANAGER_PORT=8080
  worker-7:
    container_name: worker-7
    image: md5crack-worker
    build:
      context: .
      dockerfile: worker/Dockerfile
    networks:
      - md5crack-network
    environment:
      - MANAGER_HOST=manager
      - MANAGER_PORT=8080

networks:
  md5crack-network:
    driver: bridge
