ktor:
    application:
        modules:
            - ru.nsu.dsi.md5.ApplicationKt.module
        manager:
            host: "$MANAGER_HOST:localhost"
            port: "$MANAGER_PORT:8080"
        worker-id: "$WORKER_ID:0"
    deployment:
        port: 8081

