ktor:
    application:
        modules:
            - ru.nsu.dsi.md5.ApplicationKt.module
        manager:
            workers: "$WORKERS_COUNT:1"
        database:
            connection: "$DB_URI:mongodb://md5crack:goga123@localhost:27027"
            name: md5-mongo
        rabbitmq:
            uri: "$RABBIT_URI:amqp://md5crack:goga123@localhost:5672"
    deployment:
        port: 8080
